/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessConfiguration: () => import('#controllers/access_configuration_controller'),
  AccessTokens: () => import('#controllers/access_tokens_controller'),
  AuditEvents: () => import('#controllers/audit_events_controller'),
  EvidencePackages: () => import('#controllers/evidence_packages_controller'),
  Health: () => import('#controllers/health_controller'),
  IntegrationHealth: () => import('#controllers/integration_health_controller'),
  IntegrationMappings: () => import('#controllers/integration_mappings_controller'),
  MedicationProducts: () => import('#controllers/medication_products_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  PartnerFeeds: () => import('#controllers/partner_feeds_controller'),
  Profile: () => import('#controllers/profile_controller'),
  QuarantineRecords: () => import('#controllers/quarantine_records_controller'),
  QuarantineReprocessings: () => import('#controllers/quarantine_reprocessings_controller'),
  RiskSignals: () => import('#controllers/risk_signals_controller'),
  Sites: () => import('#controllers/sites_controller'),
  StockPositions: () => import('#controllers/stock_positions_controller'),
  WorkforceAuthContext: () => import('#controllers/workforce_auth_context_controller'),
}
