/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class WorkerHeartbeatSchema extends BaseModel {
  static $columns = ['createdAt', 'lastSeenAt', 'metadata', 'name', 'updatedAt'] as const
  $columns = WorkerHeartbeatSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare lastSeenAt: DateTime
  @column()
  declare metadata: any
  @column({ isPrimary: true })
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class MedicationProductSchema extends BaseModel {
  static $columns = ['activeIngredient', 'createdAt', 'dosageForm', 'id', 'labelerName', 'marketingCategory', 'ndc', 'nonproprietaryName', 'normalizedNdc', 'productType', 'proprietaryName', 'route', 'source', 'strength', 'updatedAt'] as const
  $columns = MedicationProductSchema.$columns
  @column()
  declare activeIngredient: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare dosageForm: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare labelerName: string
  @column()
  declare marketingCategory: string
  @column()
  declare ndc: string
  @column()
  declare nonproprietaryName: string
  @column()
  declare normalizedNdc: string
  @column()
  declare productType: string
  @column()
  declare proprietaryName: string
  @column()
  declare route: string
  @column()
  declare source: string
  @column()
  declare strength: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class OrganizationSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'name', 'organizationKey', 'status', 'type', 'updatedAt'] as const
  $columns = OrganizationSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare organizationKey: string
  @column()
  declare status: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class SiteSchema extends BaseModel {
  static $columns = ['city', 'country', 'createdAt', 'id', 'name', 'organizationId', 'organizationKey', 'region', 'siteKey', 'status', 'type', 'updatedAt'] as const
  $columns = SiteSchema.$columns
  @column()
  declare city: string
  @column()
  declare country: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare organizationId: number
  @column()
  declare organizationKey: string
  @column()
  declare region: string
  @column()
  declare siteKey: string
  @column()
  declare status: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class MedicationLotSchema extends BaseModel {
  static $columns = ['createdAt', 'expirationDate', 'id', 'lotNumber', 'medicationProductId', 'source', 'updatedAt'] as const
  $columns = MedicationLotSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.date()
  declare expirationDate: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare lotNumber: string
  @column()
  declare medicationProductId: number
  @column()
  declare source: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
